let data=[];const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fetch('data/specimens.json').then(r=>r.json()).then(d=>{data=d;init()});
function init(){fill('#category',[...new Set(data.map(x=>x.collection_type))]);fill('#ownership',[...new Set(data.map(x=>x.ownership_collection).filter(Boolean))]);['#search','#category','#ownership','#photos'].forEach(s=>$(s).addEventListener(s==='#search'?'input':'change',render));$('#aboutBtn').onclick=()=>$('#about').showModal();$('#statsBtn').onclick=showStats;document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#totalCount').textContent=data.length;$('#photoCount').textContent=data.filter(x=>x.photos.length).length;render()}
function fill(sel,vals){vals.sort().forEach(v=>$(sel).insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`))}
function filtered(){let q=$('#search').value.toLowerCase().trim(),c=$('#category').value,o=$('#ownership').value,p=$('#photos').value;return data.filter(x=>{let hay=[x.specimen_code,x.name,x.classification,x.identification,x.locality,x.provenance,x.notes,x.mineral_group].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!c||x.collection_type===c)&&(!o||x.ownership_collection===o)&&(!p||(p==='yes'?x.photos.length>0:x.photos.length===0))})}
function render(){let a=filtered();$('#resultCount').textContent=`${a.length} specimen${a.length===1?'':'s'}`;$('#grid').innerHTML=a.map(x=>{let img=x.photos.find(p=>p.is_primary)||x.photos[0];return `<article class="card" onclick="openDetail(${x.id})"><div class="photo" ${img?.web_path?`style="background-image:url('${img.web_path}')"`:''}>${img?.web_path?'':'No photograph'}</div><div class="meta"><span class="code">${esc(x.specimen_code)}</span><h3>${esc(x.name)}</h3><p>${esc(x.locality||'Locality unknown')}</p><span class="badge">${esc(x.collection_type)}</span></div></article>`}).join('')}
function val(label,v){return v?`<div class="field"><b>${label}</b>${esc(v)}</div>`:''}
window.openDetail=id=>{let x=data.find(y=>y.id===id),imgs=x.photos.filter(p=>p.web_path).map(p=>`<img src="${p.web_path}" alt="${esc(x.name)}">`).join('');$('#detailBody').innerHTML=`<span class="code">${esc(x.specimen_code)}</span><h2>${esc(x.name)}</h2><p>${esc(x.collection_type)} · ${esc(x.ownership_collection||'Collection not assigned')}</p>${imgs?`<div class="gallery">${imgs}</div>`:'<div class="placeholder">No photograph uploaded.</div>'}<div class="detail-grid">${val('Identification',x.identification)}${val('Classification',x.classification)}${val('Locality',x.locality)}${val('Accessory minerals',x.accessory_minerals)}${val('Color',x.color)}${val('Luster',x.luster)}${val('Size',x.size_class)}${val('Formula',x.formula)}${val('Crystal system',x.crystal_system)}${val('Mineral group',x.mineral_group)}${val('Provenance',x.provenance)}${val('Date acquired',x.acquisition_date)}${val('Price',x.price_display)}${val('Status',x.status)}${val('Display location',x.display_location)}${val('Notes',x.notes)}${val('Story',x.story)}</div><h3>Related materials</h3><div class="placeholder">Historical labels, specimen-specific articles, and research documents will appear here when linked.</div>`;$('#detail').showModal()}
function showStats(){let cats=count('collection_type'),owners=count('ownership_collection');$('#statsBody').innerHTML=`<div class="stats-grid"><div class="statbox"><strong>${data.length}</strong>Total specimens</div><div class="statbox"><strong>${data.reduce((n,x)=>n+x.photos.length,0)}</strong>Total photographs</div><div class="statbox"><strong>${data.filter(x=>x.photos.length).length}</strong>Specimens photographed</div><div class="statbox"><strong>${data.filter(x=>x.photos.length===0).length}</strong>Awaiting photos</div></div><h3>By collection</h3>${list(cats)}<h3>By ownership</h3>${list(owners)}`;$('#stats').showModal()}
function count(k){return data.reduce((a,x)=>{let v=x[k]||'Unassigned';a[v]=(a[v]||0)+1;return a},{})}function list(o){return Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="field"><b>${esc(k)}</b>${v}</div>`).join('')}